const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Expo config plugin that adds a post_install fix for the fmt 11.0.2 pod.
 *
 * fmt 11.0.2 uses C++20 `consteval` which is incompatible with newer
 * Xcode / Clang versions. Downgrading to C++17 for that pod alone avoids
 * the build error without affecting the rest of the project.
 *
 * Because ios/Podfile is regenerated by `expo prebuild`, manual edits are
 * lost. This plugin injects the fix automatically.
 */
const withFmtFix = (config) => {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );
      let podfile = fs.readFileSync(podfilePath, "utf8");

      const tag = "fmt-cxx17-fix";
      const marker = `# @generated begin ${tag}`;

      // Idempotent — skip if already present
      if (podfile.includes(marker)) {
        return config;
      }

      const snippet = [
        "",
        `    ${marker}`,
        "    # Fix fmt 11.0.2 consteval error with newer Xcode/Clang versions",
        "    installer.pods_project.targets.each do |target|",
        "      if target.name == 'fmt'",
        "        target.build_configurations.each do |config|",
        "          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'",
        "        end",
        "      end",
        "    end",
        `    # @generated end ${tag}`,
      ].join("\n");

      // Insert right after `post_install do |installer|`
      const anchor = "post_install do |installer|";
      const anchorIndex = podfile.indexOf(anchor);
      if (anchorIndex === -1) {
        console.warn(
          "[withFmtFix] Could not find post_install block in Podfile — skipping"
        );
        return config;
      }

      const insertPos = anchorIndex + anchor.length;
      podfile =
        podfile.slice(0, insertPos) + snippet + podfile.slice(insertPos);

      fs.writeFileSync(podfilePath, podfile, "utf8");
      return config;
    },
  ]);
};

module.exports = withFmtFix;
