const { withAppDelegate } = require("expo/config-plugins");

/**
 * Expo config plugin that keeps Siri's App Shortcut parameter snapshot fresh.
 *
 * The per-tag voice command ("Start a <tag> session in Bittersweet") uses a
 * dynamic AppEntity parameter whose candidate values come from
 * TagEntityQuery.suggestedEntities(). iOS caches that snapshot and only re-queries
 * occasionally. On a fresh install the first snapshot is taken before the JS side
 * has synced the tag list into the App Group, so it's EMPTY — and iOS drops a
 * parameterized phrase that has no possible values, producing
 * "Bittersweet hasn't added support for that with Siri." (The parameter-less Stop
 * command is unaffected, which is how we isolated this.)
 *
 * Fix: call BittersweetAppShortcuts.updateAppShortcutParameters() on every
 * foreground. By then the persisted widgetTagList (written by WidgetService on a
 * prior launch) is present, so suggestedEntities() returns real tags and the Start
 * phrase becomes available. updateAppShortcutParameters / AppShortcutsProvider need
 * iOS 16+, but BittersweetAppShortcuts is gated to iOS 17 (it wraps the iOS-17
 * LiveActivityIntents), so the call is guarded accordingly.
 *
 * AppDelegate.swift is regenerated by prebuild, so this injection must live in a
 * plugin rather than being hand-edited into ios/.
 */
const REFRESH_METHOD = `
  // Injected by withSiriShortcutsRefresh: keep Siri's App Shortcut parameter
  // (focus tags) snapshot current so the per-tag "Start" phrase stays available.
  public override func applicationDidBecomeActive(_ application: UIApplication) {
    super.applicationDidBecomeActive(application)
    if #available(iOS 17.0, *) {
      BittersweetAppShortcuts.updateAppShortcutParameters()
    }
  }
`;

module.exports = function withSiriShortcutsRefresh(config) {
  return withAppDelegate(config, (cfg) => {
    let contents = cfg.modResults.contents;

    if (cfg.modResults.language !== "swift") {
      throw new Error(
        "withSiriShortcutsRefresh expected a Swift AppDelegate but found: " +
          cfg.modResults.language
      );
    }

    // Idempotent: don't inject twice across repeated prebuilds.
    if (contents.includes("withSiriShortcutsRefresh")) {
      return cfg;
    }

    // 1. Ensure AppIntents is imported (BittersweetAppShortcuts lives there).
    if (!/^import AppIntents$/m.test(contents)) {
      contents = contents.replace(
        /^import Expo$/m,
        "import Expo\nimport AppIntents"
      );
    }

    // 2. Insert the override right after the AppDelegate class opening brace.
    const anchor = "public class AppDelegate: ExpoAppDelegate {";
    if (!contents.includes(anchor)) {
      throw new Error(
        "withSiriShortcutsRefresh could not find the AppDelegate class declaration to anchor on."
      );
    }
    contents = contents.replace(anchor, anchor + "\n" + REFRESH_METHOD);

    cfg.modResults.contents = contents;
    return cfg;
  });
};
