const { withAppDelegate } = require("expo/config-plugins");

/**
 * Expo config plugin that keeps Siri's App Shortcut parameter snapshot fresh.
 *
 * The per-tag voice command ("Start a <tag> session in Bittersweet") uses a
 * dynamic AppEntity parameter whose candidate values come from
 * TagEntityQuery.suggestedEntities(). iOS caches that snapshot and only re-queries
 * occasionally. On a fresh install the first snapshot is taken before the JS side
 * has synced the tag list into the App Group, so it's EMPTY — and iOS drops a
 * parameterized phrase that has no possible values, producing
 * "Bittersweet hasn't added support for that with Siri." (The parameter-less Stop
 * command is unaffected, which is how we isolated this.)
 *
 * Fix: call BittersweetAppShortcuts.updateAppShortcutParameters() on every
 * foreground. By then the persisted widgetTagList (written by WidgetService on a
 * prior launch) is present, so suggestedEntities() returns real tags and the Start
 * phrase becomes available. updateAppShortcutParameters / AppShortcutsProvider need
 * iOS 16+, but BittersweetAppShortcuts is gated to iOS 17 (it wraps the iOS-17
 * LiveActivityIntents), so the call is guarded accordingly.
 *
 * AppDelegate.swift is regenerated by prebuild, so this injection must live in a
 * plugin rather than being hand-edited into ios/.
 */
const REFRESH_METHOD = `
  // Injected by withSiriShortcutsRefresh: keep Siri's App Shortcut parameter
  // (focus tags) snapshot current so the per-tag "Start" phrase stays available.
  public override func applicationDidBecomeActive(_ application: UIApplication) {
    super.applicationDidBecomeActive(application)
    if #available(iOS 17.0, *) {
      BittersweetAppShortcuts.updateAppShortcutParameters()
    }
  }
`;

module.exports = function withSiriShortcutsRefresh(config) {
  return withAppDelegate(config, (cfg) => {
    let contents = cfg.modResults.contents;

    if (cfg.modResults.language !== "swift") {
      throw new Error(
        "withSiriShortcutsRefresh expected a Swift AppDelegate but found: " +
          cfg.modResults.language
      );
    }

    // Idempotent: don't inject twice across repeated prebuilds.
    if (contents.includes("withSiriShortcutsRefresh")) {
      return cfg;
    }

    // 1. Ensure AppIntents is imported (BittersweetAppShortcuts lives there).
    //    SDK 56 emits `internal import Expo`, earlier SDKs plain `import Expo`,
    //    so tolerate an optional access modifier on both the test and the anchor.
    const IMPORT_RE = /^((?:internal |public |package )?import Expo)$/m;
    if (!/^(?:internal |public |package )?import AppIntents$/m.test(contents)) {
      if (!IMPORT_RE.test(contents)) {
        throw new Error(
          "withSiriShortcutsRefresh could not find the `import Expo` line to anchor the AppIntents import on."
        );
      }
      contents = contents.replace(IMPORT_RE, "$1\nimport AppIntents");
    }

    // 2. Insert the override right after the AppDelegate class opening brace.
    //    SDK 56 dropped the `public` modifier and moved to `@main`, so match the
    //    declaration by shape rather than as a fixed string.
    const ANCHOR_RE =
      /((?:public |internal |final )*class AppDelegate\s*:\s*ExpoAppDelegate\s*\{)/;
    if (!ANCHOR_RE.test(contents)) {
      throw new Error(
        "withSiriShortcutsRefresh could not find the AppDelegate class declaration to anchor on."
      );
    }
    contents = contents.replace(ANCHOR_RE, "$1\n" + REFRESH_METHOD);

    cfg.modResults.contents = contents;
    return cfg;
  });
};
