import { FC, useState, useEffect } from 'react';
import { View, Pressable, TextInput } from 'react-native';
import { Typography } from '../../ui/Typography';
import { Slider } from '../../ui/Slider';
import { Toggle } from '../../ui/Toggle';
import { HorizontalTagSelector } from '../../focus/TagSelector';
import { useFocus } from '../../../store';
import { FocusGoal } from '../../../store/types';

type GoalPeriod = 'daily' | 'weekly' | 'monthly';

const MAX_HOURS: Record<GoalPeriod, number> = {
  daily: 12,
  weekly: 84,
  monthly: 360,
};

const STEP_HOURS: Record<GoalPeriod, number> = {
  daily: 0.5,
  weekly: 1,
  monthly: 5,
};

interface FocusGoalFormProps {
  onSubmit: (goal: {
    name: string;
    targetMinutes: number;
    period: GoalPeriod;
    tagIds: string[];
    isRepeating: boolean;
    showTotalHours: boolean;
  }) => void;
  onCancel: () => void;
  editingGoal?: FocusGoal;
}

export const FocusGoalForm: FC<FocusGoalFormProps> = ({
  onSubmit,
  onCancel,
  editingGoal,
}) => {
  const [targetHours, setTargetHours] = useState(4);
  const [period, setPeriod] = useState<GoalPeriod>('daily');
  const [selectedTagIds, setSelectedTagIds] = useState<string[]>([]);
  const [customGoalName, setCustomGoalName] = useState('');
  const [isRepeating, setIsRepeating] = useState(true);
  const [showTotalHours, setShowTotalHours] = useState(true);

  // Get tags from store
  const { tags } = useFocus();

  // Convert normalized tags to array
  const availableTags = (tags.allIds || []).map(id => tags.byId[id]).filter(Boolean);

  // Populate form fields when editing
  useEffect(() => {
    if (editingGoal) {
      setTargetHours(Math.round(editingGoal.targetMinutes / 60 * 2) / 2); // round to nearest 0.5
      // Migrate yearly to monthly for editing
      const goalPeriod = editingGoal.period === ('yearly' as string) ? 'monthly' : editingGoal.period;
      setPeriod(goalPeriod as GoalPeriod);
      setSelectedTagIds((editingGoal as any).tagIds || []);
      setIsRepeating(editingGoal.isRepeating ?? true);
      setShowTotalHours(editingGoal.showTotalHours ?? false);

      // Set custom name if it's not the auto-generated pattern (check both old and new formats)
      const goalTagIds = (editingGoal as any).tagIds || [];
      const periodPrefix = editingGoal.period.charAt(0).toUpperCase() + editingGoal.period.slice(1);
      let tagDisplayName = 'Focus';
      if (goalTagIds.length === 1) {
        const tag = tags.byId[goalTagIds[0]];
        tagDisplayName = tag?.name || 'Focus';
      }
      const newAutoName = goalTagIds.length === 1 ? `${tagDisplayName} Goal` : 'Focus Goal';
      const oldAutoName = goalTagIds.length === 1
        ? `${periodPrefix} ${tagDisplayName} Goal`
        : `${periodPrefix} Focus Goal`;

      const isAutoGenerated = editingGoal.name === newAutoName || editingGoal.name === oldAutoName;
      setCustomGoalName(isAutoGenerated ? '' : editingGoal.name);
    } else {
      // Reset to defaults when creating new goal
      setTargetHours(4);
      setPeriod('daily');
      setSelectedTagIds([]);
      setCustomGoalName('');
      setIsRepeating(true);
      setShowTotalHours(true);
    }
  }, [editingGoal, tags.byId]);

  // Clamp targetHours and snap to step when period changes
  useEffect(() => {
    const max = MAX_HOURS[period];
    const step = STEP_HOURS[period];
    let clamped = Math.min(targetHours, max);
    // Snap to nearest valid step
    clamped = Math.round(clamped / step) * step;
    clamped = Math.max(step, clamped); // at least one step
    if (clamped !== targetHours) {
      setTargetHours(clamped);
    }
  }, [period]);

  const handleSubmit = () => {
    const totalMinutes = targetHours * 60;

    // Generate goal name based on tag selection
    let goalName = customGoalName.trim();

    if (!goalName) {
      if (selectedTagIds.length === 1) {
        // Single tag: use "<tag> Goal" format
        const tag = availableTags.find(t => t.id === selectedTagIds[0]);
        const tagDisplayName = tag?.name || 'Focus';
        goalName = `${tagDisplayName} Goal`;
      } else {
        // Multiple tags or no tags: use generic format
        goalName = 'Focus Goal';
      }
    }

    onSubmit({
      name: goalName,
      targetMinutes: totalMinutes,
      period,
      tagIds: selectedTagIds,
      isRepeating,
      showTotalHours,
    });
  };

  const toggleTag = (tagId: string) => {
    setSelectedTagIds(prev =>
      prev.includes(tagId)
        ? prev.filter(id => id !== tagId)
        : [...prev, tagId]
    );
  };

  const isValid = targetHours > 0 && selectedTagIds.length > 0;

  const formatSliderValue = (hours: number): string => {
    const wholeHours = Math.floor(hours);
    const minutes = Math.round((hours - wholeHours) * 60);
    if (minutes === 0) return `${wholeHours}h`;
    return `${wholeHours}h ${minutes}m`;
  };

  return (
    <View className="gap-y-4">
      {/* Goal Name */}
      <View>
        <Typography variant="subtitle-16" color="white" className="mb-2">
          Goal Name
        </Typography>
        <TextInput
          value={customGoalName}
          onChangeText={setCustomGoalName}
          placeholder={
            selectedTagIds.length === 1
              ? `${availableTags.find(t => t.id === selectedTagIds[0])?.name || 'Focus'} Goal`
              : 'Focus Goal'
          }
          placeholderTextColor="#6B7280"
          className="bg-dark-border rounded-xl p-4 text-white text-base"
          style={{ fontFamily: 'Poppins-Regular' }}
        />
      </View>

      {/* Tag Selection */}
      <View>
        <Typography variant="subtitle-16" color="white" className="mb-2">
          Tags *
        </Typography>
        <HorizontalTagSelector
          tags={availableTags}
          selectedTags={selectedTagIds}
          onTagSelect={toggleTag}
        />
      </View>

      {/* Time Period */}
      <View>
        <Typography variant="subtitle-16" color="white" className="mb-2">
          Time Period
        </Typography>
        <View className="flex-row gap-x-2">
          {(['daily', 'weekly', 'monthly'] as const).map((p) => (
            <Pressable
              key={p}
              onPress={() => setPeriod(p)}
              className={`flex-1 py-2.5 rounded-xl ${
                period === p ? 'bg-primary' : 'bg-dark-border'
              }`}
            >
              <Typography
                variant="body-14"
                className="text-center text-white"
              >
                {p.charAt(0).toUpperCase() + p.slice(1)}
              </Typography>
            </Pressable>
          ))}
        </View>
      </View>

      {/* Target Duration — Slider */}
      <View>
        <Typography variant="subtitle-16" color="white" className="mb-2">
          Target Duration
        </Typography>
        <View className="bg-dark-border rounded-xl px-4 py-3 items-center">
          <Typography variant="headline-20" color="white" className="mb-1">
            {formatSliderValue(targetHours)}
          </Typography>
          <Slider
            value={targetHours}
            minimumValue={STEP_HOURS[period]}
            maximumValue={MAX_HOURS[period]}
            step={STEP_HOURS[period]}
            onValueChange={setTargetHours}
            unit="h"
          />
        </View>
      </View>

      {/* Settings */}
      <View className="bg-dark-border rounded-xl">
        <View className="flex-row items-center justify-between p-4">
          <View className="flex-1 mr-3">
            <Typography variant="subtitle-16" color="white">
              Repeat this goal
            </Typography>
            <Typography variant="body-12" color="secondary" className="mt-0.5">
              Track consistency across periods
            </Typography>
          </View>
          <Toggle value={isRepeating} onValueChange={setIsRepeating} />
        </View>
        <View className="h-px bg-dark-surface mx-4" />
        <View className="flex-row items-center justify-between p-4">
          <View className="flex-1 mr-3">
            <Typography variant="subtitle-16" color="white">
              Show total hours
            </Typography>
            <Typography variant="body-12" color="secondary" className="mt-0.5">
              Display cumulative hours in the streaks view
            </Typography>
          </View>
          <Toggle value={showTotalHours} onValueChange={setShowTotalHours} />
        </View>
      </View>

      {/* Action Buttons */}
      <View className="flex-row gap-x-3 pt-1 pb-4">
        <Pressable
          onPress={onCancel}
          className="flex-1 bg-dark-border rounded-xl py-4 active:opacity-70"
        >
          <Typography variant="body-14" color="white" className="text-center">
            Cancel
          </Typography>
        </Pressable>
        <Pressable
          onPress={handleSubmit}
          disabled={!isValid}
          className={`flex-1 rounded-xl py-4 active:opacity-70 ${
            isValid ? 'bg-primary' : 'bg-dark-border opacity-50'
          }`}
        >
          <Typography
            variant="body-14"
            color="white"
            className="text-center"
          >
            {editingGoal ? 'Update Goal' : 'Create Goal'}
          </Typography>
        </Pressable>
      </View>
    </View>
  );
};
